/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VacanciesRouteImport } from './routes/vacancies'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdmintrackingRouteImport } from './routes/admintracking'
import { Route as AdminsettingsRouteImport } from './routes/adminsettings'
import { Route as AdminservicesRouteImport } from './routes/adminservices'
import { Route as AdminquotesRouteImport } from './routes/adminquotes'
import { Route as AdminnotificationsRouteImport } from './routes/adminnotifications'
import { Route as AdminjobsRouteImport } from './routes/adminjobs'
import { Route as AdmininvoicesRouteImport } from './routes/admininvoices'
import { Route as AdmindashboardRouteImport } from './routes/admindashboard'
import { Route as AdmincustomersRouteImport } from './routes/admincustomers'
import { Route as AdminanalyticsRouteImport } from './routes/adminanalytics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as QuoteSuccessRouteImport } from './routes/quote_.success'
import { Route as QuoteProcessingRouteImport } from './routes/quote_.processing'
import { Route as DashboardQuotesRouteImport } from './routes/dashboard.quotes'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'

const VacanciesRoute = VacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmintrackingRoute = AdmintrackingRouteImport.update({
  id: '/admintracking',
  path: '/admintracking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsettingsRoute = AdminsettingsRouteImport.update({
  id: '/adminsettings',
  path: '/adminsettings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminservicesRoute = AdminservicesRouteImport.update({
  id: '/adminservices',
  path: '/adminservices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminquotesRoute = AdminquotesRouteImport.update({
  id: '/adminquotes',
  path: '/adminquotes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminnotificationsRoute = AdminnotificationsRouteImport.update({
  id: '/adminnotifications',
  path: '/adminnotifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminjobsRoute = AdminjobsRouteImport.update({
  id: '/adminjobs',
  path: '/adminjobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmininvoicesRoute = AdmininvoicesRouteImport.update({
  id: '/admininvoices',
  path: '/admininvoices',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmindashboardRoute = AdmindashboardRouteImport.update({
  id: '/admindashboard',
  path: '/admindashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmincustomersRoute = AdmincustomersRouteImport.update({
  id: '/admincustomers',
  path: '/admincustomers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminanalyticsRoute = AdminanalyticsRouteImport.update({
  id: '/adminanalytics',
  path: '/adminanalytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const QuoteSuccessRoute = QuoteSuccessRouteImport.update({
  id: '/quote_/success',
  path: '/quote/success',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteProcessingRoute = QuoteProcessingRouteImport.update({
  id: '/quote_/processing',
  path: '/quote/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQuotesRoute = DashboardQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adminanalytics': typeof AdminanalyticsRoute
  '/admincustomers': typeof AdmincustomersRoute
  '/admindashboard': typeof AdmindashboardRoute
  '/admininvoices': typeof AdmininvoicesRoute
  '/adminjobs': typeof AdminjobsRoute
  '/adminnotifications': typeof AdminnotificationsRoute
  '/adminquotes': typeof AdminquotesRoute
  '/adminservices': typeof AdminservicesRoute
  '/adminsettings': typeof AdminsettingsRoute
  '/admintracking': typeof AdmintrackingRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/vacancies': typeof VacanciesRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/quote/processing': typeof QuoteProcessingRoute
  '/quote/success': typeof QuoteSuccessRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adminanalytics': typeof AdminanalyticsRoute
  '/admincustomers': typeof AdmincustomersRoute
  '/admindashboard': typeof AdmindashboardRoute
  '/admininvoices': typeof AdmininvoicesRoute
  '/adminjobs': typeof AdminjobsRoute
  '/adminnotifications': typeof AdminnotificationsRoute
  '/adminquotes': typeof AdminquotesRoute
  '/adminservices': typeof AdminservicesRoute
  '/adminsettings': typeof AdminsettingsRoute
  '/admintracking': typeof AdmintrackingRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faqs': typeof FaqsRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/terms': typeof TermsRoute
  '/vacancies': typeof VacanciesRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/quote/processing': typeof QuoteProcessingRoute
  '/quote/success': typeof QuoteSuccessRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/adminanalytics': typeof AdminanalyticsRoute
  '/admincustomers': typeof AdmincustomersRoute
  '/admindashboard': typeof AdmindashboardRoute
  '/admininvoices': typeof AdmininvoicesRoute
  '/adminjobs': typeof AdminjobsRoute
  '/adminnotifications': typeof AdminnotificationsRoute
  '/adminquotes': typeof AdminquotesRoute
  '/adminservices': typeof AdminservicesRoute
  '/adminsettings': typeof AdminsettingsRoute
  '/admintracking': typeof AdmintrackingRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/services': typeof ServicesRouteWithChildren
  '/terms': typeof TermsRoute
  '/vacancies': typeof VacanciesRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/quote_/processing': typeof QuoteProcessingRoute
  '/quote_/success': typeof QuoteSuccessRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/adminanalytics'
    | '/admincustomers'
    | '/admindashboard'
    | '/admininvoices'
    | '/adminjobs'
    | '/adminnotifications'
    | '/adminquotes'
    | '/adminservices'
    | '/adminsettings'
    | '/admintracking'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/faqs'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/terms'
    | '/vacancies'
    | '/dashboard/invoices'
    | '/dashboard/quotes'
    | '/quote/processing'
    | '/quote/success'
    | '/services/$slug'
    | '/dashboard/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/adminanalytics'
    | '/admincustomers'
    | '/admindashboard'
    | '/admininvoices'
    | '/adminjobs'
    | '/adminnotifications'
    | '/adminquotes'
    | '/adminservices'
    | '/adminsettings'
    | '/admintracking'
    | '/contact'
    | '/cookies'
    | '/faqs'
    | '/privacy'
    | '/quote'
    | '/terms'
    | '/vacancies'
    | '/dashboard/invoices'
    | '/dashboard/quotes'
    | '/quote/processing'
    | '/quote/success'
    | '/services/$slug'
    | '/dashboard'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/adminanalytics'
    | '/admincustomers'
    | '/admindashboard'
    | '/admininvoices'
    | '/adminjobs'
    | '/adminnotifications'
    | '/adminquotes'
    | '/adminservices'
    | '/adminsettings'
    | '/admintracking'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/faqs'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/terms'
    | '/vacancies'
    | '/dashboard/invoices'
    | '/dashboard/quotes'
    | '/quote_/processing'
    | '/quote_/success'
    | '/services/$slug'
    | '/dashboard/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminanalyticsRoute: typeof AdminanalyticsRoute
  AdmincustomersRoute: typeof AdmincustomersRoute
  AdmindashboardRoute: typeof AdmindashboardRoute
  AdmininvoicesRoute: typeof AdmininvoicesRoute
  AdminjobsRoute: typeof AdminjobsRoute
  AdminnotificationsRoute: typeof AdminnotificationsRoute
  AdminquotesRoute: typeof AdminquotesRoute
  AdminservicesRoute: typeof AdminservicesRoute
  AdminsettingsRoute: typeof AdminsettingsRoute
  AdmintrackingRoute: typeof AdmintrackingRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqsRoute: typeof FaqsRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  TermsRoute: typeof TermsRoute
  VacanciesRoute: typeof VacanciesRoute
  QuoteProcessingRoute: typeof QuoteProcessingRoute
  QuoteSuccessRoute: typeof QuoteSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vacancies': {
      id: '/vacancies'
      path: '/vacancies'
      fullPath: '/vacancies'
      preLoaderRoute: typeof VacanciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admintracking': {
      id: '/admintracking'
      path: '/admintracking'
      fullPath: '/admintracking'
      preLoaderRoute: typeof AdmintrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminsettings': {
      id: '/adminsettings'
      path: '/adminsettings'
      fullPath: '/adminsettings'
      preLoaderRoute: typeof AdminsettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminservices': {
      id: '/adminservices'
      path: '/adminservices'
      fullPath: '/adminservices'
      preLoaderRoute: typeof AdminservicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminquotes': {
      id: '/adminquotes'
      path: '/adminquotes'
      fullPath: '/adminquotes'
      preLoaderRoute: typeof AdminquotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminnotifications': {
      id: '/adminnotifications'
      path: '/adminnotifications'
      fullPath: '/adminnotifications'
      preLoaderRoute: typeof AdminnotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminjobs': {
      id: '/adminjobs'
      path: '/adminjobs'
      fullPath: '/adminjobs'
      preLoaderRoute: typeof AdminjobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admininvoices': {
      id: '/admininvoices'
      path: '/admininvoices'
      fullPath: '/admininvoices'
      preLoaderRoute: typeof AdmininvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admindashboard': {
      id: '/admindashboard'
      path: '/admindashboard'
      fullPath: '/admindashboard'
      preLoaderRoute: typeof AdmindashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admincustomers': {
      id: '/admincustomers'
      path: '/admincustomers'
      fullPath: '/admincustomers'
      preLoaderRoute: typeof AdmincustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminanalytics': {
      id: '/adminanalytics'
      path: '/adminanalytics'
      fullPath: '/adminanalytics'
      preLoaderRoute: typeof AdminanalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/quote_/success': {
      id: '/quote_/success'
      path: '/quote/success'
      fullPath: '/quote/success'
      preLoaderRoute: typeof QuoteSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote_/processing': {
      id: '/quote_/processing'
      path: '/quote/processing'
      fullPath: '/quote/processing'
      preLoaderRoute: typeof QuoteProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/quotes': {
      id: '/dashboard/quotes'
      path: '/quotes'
      fullPath: '/dashboard/quotes'
      preLoaderRoute: typeof DashboardQuotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardQuotesRoute: typeof DashboardQuotesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardQuotesRoute: DashboardQuotesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminanalyticsRoute: AdminanalyticsRoute,
  AdmincustomersRoute: AdmincustomersRoute,
  AdmindashboardRoute: AdmindashboardRoute,
  AdmininvoicesRoute: AdmininvoicesRoute,
  AdminjobsRoute: AdminjobsRoute,
  AdminnotificationsRoute: AdminnotificationsRoute,
  AdminquotesRoute: AdminquotesRoute,
  AdminservicesRoute: AdminservicesRoute,
  AdminsettingsRoute: AdminsettingsRoute,
  AdmintrackingRoute: AdmintrackingRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqsRoute: FaqsRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ServicesRoute: ServicesRouteWithChildren,
  TermsRoute: TermsRoute,
  VacanciesRoute: VacanciesRoute,
  QuoteProcessingRoute: QuoteProcessingRoute,
  QuoteSuccessRoute: QuoteSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
