/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketRouteImport } from './routes/ticket'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as UserRouteImport } from './routes/_user'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as QuoteSuccessRouteImport } from './routes/quote.success'
import { Route as QuoteProcessingRouteImport } from './routes/quote.processing'
import { Route as DashboardQuotesRouteImport } from './routes/dashboard.quotes'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as UserSetnewpasswordRouteImport } from './routes/_user.setnewpassword'
import { Route as UserRegisterRouteImport } from './routes/_user.register'
import { Route as UserLoginRouteImport } from './routes/_user.login'
import { Route as UserForgotpasswordRouteImport } from './routes/_user.forgotpassword'
import { Route as AuthAdmintrackingRouteImport } from './routes/_auth.admintracking'
import { Route as AuthAdminsettingsRouteImport } from './routes/_auth.adminsettings'
import { Route as AuthAdminservicesRouteImport } from './routes/_auth.adminservices'
import { Route as AuthAdminquotesRouteImport } from './routes/_auth.adminquotes'
import { Route as AuthAdminnotificationsRouteImport } from './routes/_auth.adminnotifications'
import { Route as AuthAdminjobsRouteImport } from './routes/_auth.adminjobs'
import { Route as AuthAdmininvoicesRouteImport } from './routes/_auth.admininvoices'
import { Route as AuthAdmindashboardRouteImport } from './routes/_auth.admindashboard'
import { Route as AuthAdmincustomersRouteImport } from './routes/_auth.admincustomers'
import { Route as AuthAdminanalyticsRouteImport } from './routes/_auth.adminanalytics'

const TicketRoute = TicketRouteImport.update({
  id: '/ticket',
  path: '/ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const QuoteSuccessRoute = QuoteSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => QuoteRoute,
} as any)
const QuoteProcessingRoute = QuoteProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => QuoteRoute,
} as any)
const DashboardQuotesRoute = DashboardQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const UserSetnewpasswordRoute = UserSetnewpasswordRouteImport.update({
  id: '/setnewpassword',
  path: '/setnewpassword',
  getParentRoute: () => UserRoute,
} as any)
const UserRegisterRoute = UserRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => UserRoute,
} as any)
const UserLoginRoute = UserLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UserRoute,
} as any)
const UserForgotpasswordRoute = UserForgotpasswordRouteImport.update({
  id: '/forgotpassword',
  path: '/forgotpassword',
  getParentRoute: () => UserRoute,
} as any)
const AuthAdmintrackingRoute = AuthAdmintrackingRouteImport.update({
  id: '/admintracking',
  path: '/admintracking',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminsettingsRoute = AuthAdminsettingsRouteImport.update({
  id: '/adminsettings',
  path: '/adminsettings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminservicesRoute = AuthAdminservicesRouteImport.update({
  id: '/adminservices',
  path: '/adminservices',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminquotesRoute = AuthAdminquotesRouteImport.update({
  id: '/adminquotes',
  path: '/adminquotes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminnotificationsRoute = AuthAdminnotificationsRouteImport.update({
  id: '/adminnotifications',
  path: '/adminnotifications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminjobsRoute = AuthAdminjobsRouteImport.update({
  id: '/adminjobs',
  path: '/adminjobs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdmininvoicesRoute = AuthAdmininvoicesRouteImport.update({
  id: '/admininvoices',
  path: '/admininvoices',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdmindashboardRoute = AuthAdmindashboardRouteImport.update({
  id: '/admindashboard',
  path: '/admindashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdmincustomersRoute = AuthAdmincustomersRouteImport.update({
  id: '/admincustomers',
  path: '/admincustomers',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminanalyticsRoute = AuthAdminanalyticsRouteImport.update({
  id: '/adminanalytics',
  path: '/adminanalytics',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/ticket': typeof TicketRoute
  '/adminanalytics': typeof AuthAdminanalyticsRoute
  '/admincustomers': typeof AuthAdmincustomersRoute
  '/admindashboard': typeof AuthAdmindashboardRoute
  '/admininvoices': typeof AuthAdmininvoicesRoute
  '/adminjobs': typeof AuthAdminjobsRoute
  '/adminnotifications': typeof AuthAdminnotificationsRoute
  '/adminquotes': typeof AuthAdminquotesRoute
  '/adminservices': typeof AuthAdminservicesRoute
  '/adminsettings': typeof AuthAdminsettingsRoute
  '/admintracking': typeof AuthAdmintrackingRoute
  '/forgotpassword': typeof UserForgotpasswordRoute
  '/login': typeof UserLoginRoute
  '/register': typeof UserRegisterRoute
  '/setnewpassword': typeof UserSetnewpasswordRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/quote/processing': typeof QuoteProcessingRoute
  '/quote/success': typeof QuoteSuccessRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRouteWithChildren
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/ticket': typeof TicketRoute
  '/adminanalytics': typeof AuthAdminanalyticsRoute
  '/admincustomers': typeof AuthAdmincustomersRoute
  '/admindashboard': typeof AuthAdmindashboardRoute
  '/admininvoices': typeof AuthAdmininvoicesRoute
  '/adminjobs': typeof AuthAdminjobsRoute
  '/adminnotifications': typeof AuthAdminnotificationsRoute
  '/adminquotes': typeof AuthAdminquotesRoute
  '/adminservices': typeof AuthAdminservicesRoute
  '/adminsettings': typeof AuthAdminsettingsRoute
  '/admintracking': typeof AuthAdmintrackingRoute
  '/forgotpassword': typeof UserForgotpasswordRoute
  '/login': typeof UserLoginRoute
  '/register': typeof UserRegisterRoute
  '/setnewpassword': typeof UserSetnewpasswordRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/quote/processing': typeof QuoteProcessingRoute
  '/quote/success': typeof QuoteSuccessRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_user': typeof UserRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faqs': typeof FaqsRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/shop': typeof ShopRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/ticket': typeof TicketRoute
  '/_auth/adminanalytics': typeof AuthAdminanalyticsRoute
  '/_auth/admincustomers': typeof AuthAdmincustomersRoute
  '/_auth/admindashboard': typeof AuthAdmindashboardRoute
  '/_auth/admininvoices': typeof AuthAdmininvoicesRoute
  '/_auth/adminjobs': typeof AuthAdminjobsRoute
  '/_auth/adminnotifications': typeof AuthAdminnotificationsRoute
  '/_auth/adminquotes': typeof AuthAdminquotesRoute
  '/_auth/adminservices': typeof AuthAdminservicesRoute
  '/_auth/adminsettings': typeof AuthAdminsettingsRoute
  '/_auth/admintracking': typeof AuthAdmintrackingRoute
  '/_user/forgotpassword': typeof UserForgotpasswordRoute
  '/_user/login': typeof UserLoginRoute
  '/_user/register': typeof UserRegisterRoute
  '/_user/setnewpassword': typeof UserSetnewpasswordRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/quotes': typeof DashboardQuotesRoute
  '/quote/processing': typeof QuoteProcessingRoute
  '/quote/success': typeof QuoteSuccessRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faqs'
    | '/notifications'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/shop'
    | '/support'
    | '/terms'
    | '/ticket'
    | '/adminanalytics'
    | '/admincustomers'
    | '/admindashboard'
    | '/admininvoices'
    | '/adminjobs'
    | '/adminnotifications'
    | '/adminquotes'
    | '/adminservices'
    | '/adminsettings'
    | '/admintracking'
    | '/forgotpassword'
    | '/login'
    | '/register'
    | '/setnewpassword'
    | '/dashboard/invoices'
    | '/dashboard/quotes'
    | '/quote/processing'
    | '/quote/success'
    | '/services/$slug'
    | '/dashboard/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faqs'
    | '/notifications'
    | '/privacy'
    | '/quote'
    | '/shop'
    | '/support'
    | '/terms'
    | '/ticket'
    | '/adminanalytics'
    | '/admincustomers'
    | '/admindashboard'
    | '/admininvoices'
    | '/adminjobs'
    | '/adminnotifications'
    | '/adminquotes'
    | '/adminservices'
    | '/adminsettings'
    | '/admintracking'
    | '/forgotpassword'
    | '/login'
    | '/register'
    | '/setnewpassword'
    | '/dashboard/invoices'
    | '/dashboard/quotes'
    | '/quote/processing'
    | '/quote/success'
    | '/services/$slug'
    | '/dashboard'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_user'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faqs'
    | '/notifications'
    | '/privacy'
    | '/quote'
    | '/services'
    | '/shop'
    | '/support'
    | '/terms'
    | '/ticket'
    | '/_auth/adminanalytics'
    | '/_auth/admincustomers'
    | '/_auth/admindashboard'
    | '/_auth/admininvoices'
    | '/_auth/adminjobs'
    | '/_auth/adminnotifications'
    | '/_auth/adminquotes'
    | '/_auth/adminservices'
    | '/_auth/adminsettings'
    | '/_auth/admintracking'
    | '/_user/forgotpassword'
    | '/_user/login'
    | '/_user/register'
    | '/_user/setnewpassword'
    | '/dashboard/invoices'
    | '/dashboard/quotes'
    | '/quote/processing'
    | '/quote/success'
    | '/services/$slug'
    | '/dashboard/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqsRoute: typeof FaqsRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  ShopRoute: typeof ShopRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TicketRoute: typeof TicketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ticket': {
      id: '/ticket'
      path: '/ticket'
      fullPath: '/ticket'
      preLoaderRoute: typeof TicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/quote/success': {
      id: '/quote/success'
      path: '/success'
      fullPath: '/quote/success'
      preLoaderRoute: typeof QuoteSuccessRouteImport
      parentRoute: typeof QuoteRoute
    }
    '/quote/processing': {
      id: '/quote/processing'
      path: '/processing'
      fullPath: '/quote/processing'
      preLoaderRoute: typeof QuoteProcessingRouteImport
      parentRoute: typeof QuoteRoute
    }
    '/dashboard/quotes': {
      id: '/dashboard/quotes'
      path: '/quotes'
      fullPath: '/dashboard/quotes'
      preLoaderRoute: typeof DashboardQuotesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_user/setnewpassword': {
      id: '/_user/setnewpassword'
      path: '/setnewpassword'
      fullPath: '/setnewpassword'
      preLoaderRoute: typeof UserSetnewpasswordRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/register': {
      id: '/_user/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof UserRegisterRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/login': {
      id: '/_user/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/forgotpassword': {
      id: '/_user/forgotpassword'
      path: '/forgotpassword'
      fullPath: '/forgotpassword'
      preLoaderRoute: typeof UserForgotpasswordRouteImport
      parentRoute: typeof UserRoute
    }
    '/_auth/admintracking': {
      id: '/_auth/admintracking'
      path: '/admintracking'
      fullPath: '/admintracking'
      preLoaderRoute: typeof AuthAdmintrackingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/adminsettings': {
      id: '/_auth/adminsettings'
      path: '/adminsettings'
      fullPath: '/adminsettings'
      preLoaderRoute: typeof AuthAdminsettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/adminservices': {
      id: '/_auth/adminservices'
      path: '/adminservices'
      fullPath: '/adminservices'
      preLoaderRoute: typeof AuthAdminservicesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/adminquotes': {
      id: '/_auth/adminquotes'
      path: '/adminquotes'
      fullPath: '/adminquotes'
      preLoaderRoute: typeof AuthAdminquotesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/adminnotifications': {
      id: '/_auth/adminnotifications'
      path: '/adminnotifications'
      fullPath: '/adminnotifications'
      preLoaderRoute: typeof AuthAdminnotificationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/adminjobs': {
      id: '/_auth/adminjobs'
      path: '/adminjobs'
      fullPath: '/adminjobs'
      preLoaderRoute: typeof AuthAdminjobsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admininvoices': {
      id: '/_auth/admininvoices'
      path: '/admininvoices'
      fullPath: '/admininvoices'
      preLoaderRoute: typeof AuthAdmininvoicesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admindashboard': {
      id: '/_auth/admindashboard'
      path: '/admindashboard'
      fullPath: '/admindashboard'
      preLoaderRoute: typeof AuthAdmindashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admincustomers': {
      id: '/_auth/admincustomers'
      path: '/admincustomers'
      fullPath: '/admincustomers'
      preLoaderRoute: typeof AuthAdmincustomersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/adminanalytics': {
      id: '/_auth/adminanalytics'
      path: '/adminanalytics'
      fullPath: '/adminanalytics'
      preLoaderRoute: typeof AuthAdminanalyticsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAdminanalyticsRoute: typeof AuthAdminanalyticsRoute
  AuthAdmincustomersRoute: typeof AuthAdmincustomersRoute
  AuthAdmindashboardRoute: typeof AuthAdmindashboardRoute
  AuthAdmininvoicesRoute: typeof AuthAdmininvoicesRoute
  AuthAdminjobsRoute: typeof AuthAdminjobsRoute
  AuthAdminnotificationsRoute: typeof AuthAdminnotificationsRoute
  AuthAdminquotesRoute: typeof AuthAdminquotesRoute
  AuthAdminservicesRoute: typeof AuthAdminservicesRoute
  AuthAdminsettingsRoute: typeof AuthAdminsettingsRoute
  AuthAdmintrackingRoute: typeof AuthAdmintrackingRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminanalyticsRoute: AuthAdminanalyticsRoute,
  AuthAdmincustomersRoute: AuthAdmincustomersRoute,
  AuthAdmindashboardRoute: AuthAdmindashboardRoute,
  AuthAdmininvoicesRoute: AuthAdmininvoicesRoute,
  AuthAdminjobsRoute: AuthAdminjobsRoute,
  AuthAdminnotificationsRoute: AuthAdminnotificationsRoute,
  AuthAdminquotesRoute: AuthAdminquotesRoute,
  AuthAdminservicesRoute: AuthAdminservicesRoute,
  AuthAdminsettingsRoute: AuthAdminsettingsRoute,
  AuthAdmintrackingRoute: AuthAdmintrackingRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface UserRouteChildren {
  UserForgotpasswordRoute: typeof UserForgotpasswordRoute
  UserLoginRoute: typeof UserLoginRoute
  UserRegisterRoute: typeof UserRegisterRoute
  UserSetnewpasswordRoute: typeof UserSetnewpasswordRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserForgotpasswordRoute: UserForgotpasswordRoute,
  UserLoginRoute: UserLoginRoute,
  UserRegisterRoute: UserRegisterRoute,
  UserSetnewpasswordRoute: UserSetnewpasswordRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

interface DashboardRouteChildren {
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardQuotesRoute: typeof DashboardQuotesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardQuotesRoute: DashboardQuotesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface QuoteRouteChildren {
  QuoteProcessingRoute: typeof QuoteProcessingRoute
  QuoteSuccessRoute: typeof QuoteSuccessRoute
}

const QuoteRouteChildren: QuoteRouteChildren = {
  QuoteProcessingRoute: QuoteProcessingRoute,
  QuoteSuccessRoute: QuoteSuccessRoute,
}

const QuoteRouteWithChildren = QuoteRoute._addFileChildren(QuoteRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqsRoute: FaqsRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  ShopRoute: ShopRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TicketRoute: TicketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
